### ISSUE TITLE
Make preflight check

### ISSUE THREAD

**Issue by goldarte** [artem30801/CleverSwarm#13]
Make simple preflight check on each of selected copters and show the result in the preflight check status cell

**Comment by artem30801** [comment]
What checks shold be preformed in preflight check?
Should we do (separatly) active checks like arming check?

**Comment by goldarte** [comment]
Now we get information about checks but do nothing with this information

**Comment by goldarte** [comment]
Continue here: https://github.com/artem30801/CleverSwarm/issues/27
