### ISSUE TITLE
Edit buttons layout

### ISSUE THREAD

**Issue by artem30801** [artem30801/CleverSwarm#29]
For now, buttons "land" and "disarm" are dangerously near to "flip" and "takeoff". On the other hand, "emergency land" is far away. This could lead to user inconvinice, confusion and missclicks.

**Comment by goldarte** [comment]
I agree, we should change layout in more convenient way.

**Comment by goldarte** [comment]
Done here: https://github.com/artem30801/CleverSwarm/commit/d3a8d117778bb02d4756d67111eb3ea26ea6e47d
