### ISSUE TITLE
Server: table update rate is slow

### ISSUE THREAD

**Issue by goldarte** [artem30801/CleverSwarm#38]
**The bug description**
If you try to increase or decrease the column width, visual response is rather slow. If you try to check the copter, visual response of check is rather slow too

**Steps to reproduce the behavior**
Try to change any visible item of the table

**Expected behavior**
Fast response of updating the table

**Version**
 v0.3-alpha.2

**Additional information**
I think the problem is that table update function contains many checks, maybe we need to put these checks into a separate thread.

**Comment by artem30801** [comment]
Shows up on linux systems, worked well enough on windows

**Comment by artem30801** [comment]
Fixed in ca4b4aa1bfa747196beeb3efe851bfa2faa0ff3a
