### ISSUE TITLE
Add ability to remove disconnected copter from table

### ISSUE THREAD

**Issue by goldarte** [artem30801/CleverSwarm#40]
**Request description**
Some users don't like when disconnected copter is displayed in the table, I think we need to get them an option to hide disconnected copters.

**Describe the solution you'd like**
UI option to hide disconnected copters

**Comment by artem30801** [comment]
Added option for removing selected copters from table (in alpha branch)

I think auto-hiding disconnected copters could be unwanted in case of unstable connection (or any issues that leading to connection reset)

Reopen in case of other suggestions on this topic or any related issues.

**Comment by goldarte** [comment]
Needs to be tested first

**Comment by goldarte** [comment]
And then merged to master branch

**Comment by goldarte** [comment]
Tested, works. But when we turn off the power from Raspberry, server thinks that there is still a connection. How can we solve this?

**Comment by goldarte** [comment]
Also, when I try to remove copters from table manually with <remove_disconnected = True> parameter in server_config.ini, I got this error, and not all copters are removed: 
Traceback (most recent call last):
  File "server_qt.py", line 251, in remove_selected
    row_num = self.model.data_contents.index(copter)
ValueError: <copter_table_models.StatedCopterData object at 0x7f730c020f98> is not in list

**Comment by goldarte** [comment]
Fixed here: https://github.com/CopterExpress/clever-show/commit/576e1a52fad6a510d2f250772828bbfce51e85cc

Needs to be tested again.

**Comment by goldarte** [comment]
Done here: https://github.com/CopterExpress/clever-show/pull/55
Tested, works.
