### ISSUE TITLE
Add ability to rename copters directly from the server table

### ISSUE THREAD

**Issue by goldarte** [artem30801/CleverSwarm#47]
**Request description**
Add a clear solution for the user in UI to change the name of the copter.

**Describe the solution you'd like**
I think that the most convenient way is to double-click to cell with copter name, rename it and then press Enter button 

**Describe alternatives you've considered**
Another way is to add separate button called "Rename copter"

**Comment by artem30801** [comment]
Should that affect copter_id on copter?

**Comment by goldarte** [comment]
This ability is added, but now renaming id with the hostname requires restart of Raspberry Pi. We should try to do the renaming without restarting all, but with restarting only necessary services of Raspberry Pi.

**Comment by goldarte** [comment]
Added necessary settings in [SYSTEM] section of client configuration in v0.4
