### ISSUE TITLE
Incorrect start position with floor aruco-map

### ISSUE THREAD

**Issue by Ianselot** [artem30801/CleverSwarm#65]
**The bug description**
The drone doesn't see aruco-map on the floor --> 
Current position is displayed incorrect -->
Current position doesn´t match with start position -->
Аnimation can't be started.

**Steps to reproduce the behavior**
1. Put the drone on floor (floor's arucomap)
2. Power on
3. Try to click "Start animation" buttom 

**Expected behavior**
The drone must be execute the animation

**Comment by goldarte** [comment]
Added parameter for enabling or disabling position checking on server in v0.4
