### ISSUE TITLE
Self-remove drones from server's table

### ISSUE THREAD

**Issue by Ianselot** [artem30801/CleverSwarm#67]
**Request description**
If a drone was power-off it will continue to stay in the server's table. It is uncomfortable.

**Describe the solution you'd like**
The drone must be self removed from table after constant delay time without telemetry. Set the delay time as a parameter in server's config file.

**Comment by artem30801** [comment]
Problem is known and likely to be solved by tweaking sock - keepalive params
Besides, IMHO very strict dependace to the telemetry messages isn't going to end well

**Comment by goldarte** [comment]
Not tested on Raspberry

**Comment by artem30801** [comment]
Tested, fix confirmed
