### ISSUE TITLE
Software version not recognised if the project folder was downloaded as ZIP file instead of git clone

### ISSUE THREAD

**Issue by timkondratev** [artem30801/CleverSwarm#71]
**The bug description**
In drone list the version column highlights yellow. 

The server gives error:
subprocess.CalledProcessError: Command 'git log --pretty=format:'%h' -n 1' returned non-zero exit status 128.

**Steps to reproduce the behavior**
1. Go to 'https://github.com/CopterExpress/clever-show/tree/qt-gui-update'
2. Click on 'Clone or download'
3. Download ZIP
4. Run server
5. Run drone with latest software of the same branch
6. See error: subprocess.CalledProcessError: Command 'git log --pretty=format:'%h' -n 1' returned non-zero exit status 128.

**Expected behavior**
No error and green version cell.

**Version**
6b1649941bdd2cfbb9912d0fee8a86c67a9021f9

**Comment by artem30801** [comment]
Closing for now, in future we're going to release executable files of server with info of current server git version
