### ISSUE TITLE
Incorrect yaw angle during start animation

### ISSUE THREAD

**Issue by Ianselot** [artem30801/CleverSwarm#73]
**The bug description**
Random start yaw angle isn't changing during move to first point of animation

**Steps to reproduce the behavior**
1. Put a drone with random yaw on start position
2. Click on 'Start animation'
3. The drone is taking-off and moving in first animation point with current yaw angle
4. After arrived the drone is rotating to correct yaw (like first point animation yaw)
5. Execution of animation starts with incorrect yaw

**Expected behavior**
The drone takes-off and moves in first animation point with changing yaw from random started value to correct animation value

**Version**
commit 978c71d3c0cb52637450997b80da346e5df2034c

**Comment by goldarte** [comment]
Fixed and tested in v0.4
