### ISSUE TITLE
support Ardupilot

### ISSUE THREAD

**Issue by imnobodyet** [artem30801/CleverSwarm#81]
I want to use clever-show to fly drone formations, but my drones are all using Ardupilot as the fc firmware, clever-show only supports px4, can I modify some configurations of the clover to make the clever-show drone side to support Ardupilot? because it would be a lot of troubles to switch all drones to px4 . THanks!

**Comment by goldarte** [comment]
Hi! This software use clover as base framework for communicating with flight controller. Clover framework supports only px4 firmware, so you can’t make it work with ardupilot by modifying some configurations.

**Comment by artem30801** [comment]
Though it could be achieved if you modify module responsible for using Clover flight functions: https://github.com/CopterExpress/clever-show/blob/master/drone/modules/flight.py - to use functions that may interfacce with ardupilot

**Comment by imnobodyet** [comment]
> Though it could be achieved if you modify module responsible for using Clover flight functions: https://github.com/CopterExpress/clever-show/blob/master/drone/modules/flight.py - to use functions that may interfacce with ardupilot

Thanks for your help, cloud you please tell me more details about it? I'm not very familiar with the code.
